name = "trektracker"
pages_build_output_dir = "dist/public"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"

[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[[env.preview.kv_namespaces]]
binding = "KV"
preview_id = "your-preview-kv-namespace-id"
