name = "trektracker"
pages_build_output_dir = "./dist"

[pages.functions]
# This path is relative to the `pages_build_output_dir`
directory = "./functions"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"

[[env.production.kv_namespaces]]
binding = "KV"
id = "5ee25c4b47034788bd1bf549b8fcbe1c"

[[env.preview.kv_namespaces]]
binding = "KV"
id = "5ee25c4b47034788bd1bf549b8fcbe1c"
